services:
  app:
    image: stock-app:latest
    container_name: stock-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    mem_swappiness: 10
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"